-- Seed: FC 행구 roster (names, positions, back numbers only — no contact/birthdate)
-- Run in Supabase SQL editor. Idempotent: skips members already present by name.
DO $$
DECLARE tid UUID;
BEGIN
  SELECT id INTO tid FROM teams WHERE name ILIKE '%행구%' ORDER BY created_at LIMIT 1;
  IF tid IS NULL THEN RAISE EXCEPTION 'FC 행구 team not found'; END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='서은광') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '서은광', 7, 'FW', ARRAY['왼쪽윙','윙백']::text[], '7, 9, 10'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김영빈') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김영빈', 0, 'MF', ARRAY['멀티']::text[], '0'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='서명원') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '서명원', 10, 'FW', ARRAY['톱','윙']::text[], '10, 7, 30'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='유재영') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '유재영', 14, 'FW', ARRAY['윙','센백']::text[], '14'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='허창우') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '허창우', 13, 'FW', ARRAY['윙','톱','센백','윙백']::text[], '13, 4, 6'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김휘윤') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김휘윤', 4, 'DF', ARRAY['수비수','윙어']::text[], '4, 20, 39'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='안평강') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '안평강', 13, 'FW', ARRAY['윙','톱','센백','윙백']::text[], '13, 4, 6'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='박상대') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '박상대', 88, 'MF', ARRAY['미드필더']::text[], '88, 8, 99'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='최현규') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '최현규', 10, 'FW', ARRAY['공격']::text[], '10, 9, 7'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김민수') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김민수', 8, 'MF', ARRAY['미드필더']::text[], '8, 22, 13'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='송승혁') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '송승혁', 9, 'FW', ARRAY['윙포드','탑']::text[], '9, 99'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='임동원') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '임동원', 5, 'MF', ARRAY['미드필더']::text[], '5, 11, 19'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김기현') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김기현', 2, 'DF', ARRAY['윙백']::text[], '2, 6, 18'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이임수') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이임수', 15, 'DF', ARRAY['CB','CM']::text[], '15'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이창수') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이창수', 3, 'MF', ARRAY['센터백or미드필더']::text[], '3, 5, 40'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김종호') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김종호', 13, 'FW', ARRAY['윙','톱','센백','윙백']::text[], '13, 4, 6'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='최재원') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '최재원', 3, 'DF', ARRAY['윙포워드사이드백']::text[], '3, 11, 21'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이학준') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이학준', 18, 'FW', ARRAY['윙','윙백','골기퍼(?)']::text[], '18, 7, 6'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='안장현') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '안장현', 99, 'MF', ARRAY['미드필더공격']::text[], '99, 17, 25'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='천호준') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '천호준', 17, 'FW', ARRAY['센터포워드']::text[], '17'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='방태훈') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '방태훈', 1, 'GK', ARRAY['GK']::text[], '1'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='오세현') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '오세현', 3, 'DF', ARRAY['윙백']::text[], '3, 10, 17'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='박세림') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '박세림', 7, 'FW', ARRAY['윙','톱']::text[], '7, 11, 19'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='정우원') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '정우원', 6, 'MF', ARRAY['CM']::text[], '6, 16, 26'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='정요셉') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '정요셉', 1, 'DF', ARRAY['윙백']::text[], '1, 77, 2, 22, 3'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김시민') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김시민', 26, 'DF', ARRAY['윙백']::text[], '26, 3, 93'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='정승훈') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '정승훈', 93, 'MF', ARRAY['미드필더']::text[], '93, 27, 8'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='심근보') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '심근보', 8, 'MF', ARRAY['미드필더','포드','중','앙수비']::text[], '8, 17, 20'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='김영진') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '김영진', 3, 'MF', ARRAY['수비형미드필더','사이드백']::text[], '3, 5, 6, 13'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이무창') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이무창', 6, 'MF', ARRAY['MF']::text[], '6, 21'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='백한솔') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '백한솔', 9, 'FW', ARRAY['톱','공미']::text[], '9, 10, 11'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이찬형') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이찬형', 45, 'FW', NULL, '45, 20, 19'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='민혁') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '민혁', 16, 'MF', ARRAY['MF']::text[], '16, 46, 21'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='낙타') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '낙타', 77, 'FW', ARRAY['올라인드']::text[], '77, 88, 99'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이서한') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이서한', 47, 'MF', ARRAY['미드','윙']::text[], '47'); END IF;
  IF NOT EXISTS (SELECT 1 FROM players WHERE team_id=tid AND name='이성민') THEN INSERT INTO players (team_id, name, number, default_position, preferred_positions, preferred_numbers) VALUES (tid, '이성민', NULL, 'MF', ARRAY['미드']::text[], NULL); END IF;
END $$;
