import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useRouter } from 'expo-router'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Plus } from 'lucide-react-native'
import { useTheme } from '@/lib/theme-context'
import { useI18n } from '@/lib/i18n/context'
import { useAppData } from '@/hooks/useAppData'
import { formatDate } from '@/lib/utils'

export default function Matches() {
  const router = useRouter(); const theme = useTheme(); const { t } = useI18n(); const data = useAppData(); const [refreshing, setRefreshing] = useState(false)
  useEffect(() => { if (data.isLoaded && !data.userId) router.replace('/') }, [data.isLoaded, data.userId, router])
  const completed = useMemo(() => data.matches.filter(m => +new Date(m.match_date) <= Date.now()).sort((a, b) => +new Date(b.match_date) - +new Date(a.match_date)), [data.matches])
  const upcoming = useMemo(() => data.matches.filter(m => +new Date(m.match_date) > Date.now()).sort((a, b) => +new Date(a.match_date) - +new Date(b.match_date)), [data.matches])
  if (data.loading) return <View style={[s.fill, s.center, { backgroundColor: theme.bg }]}><ActivityIndicator color={theme.text} /></View>
  const canEdit = data.selectedTeam?.role === 'coach' || !!data.selectedTeam?.membership?.can_edit_matches; const wins = completed.filter(m => m.home_score > m.away_score).length; const draws = completed.filter(m => m.home_score === m.away_score).length
  const refresh = async () => { setRefreshing(true); await data.refresh(); setRefreshing(false) }
  return <SafeAreaView style={[s.fill, { backgroundColor: theme.bg }]} edges={['top']}><View style={[s.header, { backgroundColor: theme.nav, borderColor: theme.line }]}><View><Text style={[s.title, { color: theme.text }]}>{t.allMatches}</Text><Text style={{ color: theme.text3, fontSize: 12 }}>{data.selectedTeam?.name}</Text></View>{canEdit && <Pressable accessibilityRole="button" accessibilityLabel={t.newMatchRecord} style={[s.add, { backgroundColor: theme.hero }]} onPress={() => router.push('/match/new')}><Plus color={theme.accent} /></Pressable>}</View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} />}><View style={[s.stats, { backgroundColor: theme.hero }]}>{[[t.totalGames, completed.length], [t.win, wins], [t.draw, draws], [t.loss, completed.length - wins - draws]].map(([label, value]) => <View key={String(label)} style={{ flex: 1, alignItems: 'center' }}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>)}</View>{upcoming.length > 0 && <Section title={t.upcomingMatches} matches={upcoming} theme={theme} onPress={(id: string) => router.push(`/match/${id}`)} />}<Section title={t.completedMatches} matches={completed} theme={theme} onPress={(id: string) => router.push(`/match/${id}`)} empty={t.noMatches} /></ScrollView></SafeAreaView>
}

function Section({ title, matches, theme, onPress, empty }: any) { return <View style={{ gap: 9 }}><Text style={{ color: theme.text, fontWeight: '900', marginTop: 5 }}>{title}</Text>{matches.length === 0 ? <View style={[s.empty, { backgroundColor: theme.card, borderColor: theme.line }]}><Text style={{ color: theme.text3 }}>{empty}</Text></View> : matches.map((m: any) => <Pressable key={m.id} style={[s.row, { backgroundColor: theme.card, borderColor: theme.line }]} onPress={() => onPress(m.id)}><View style={[s.bar, { backgroundColor: m.home_score > m.away_score ? theme.accent : theme.line }]} /><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '800' }}>vs {m.opponent}</Text><Text style={{ color: theme.text3, fontSize: 12, marginTop: 3 }}>{formatDate(m.match_date)}{m.location ? ` · ${m.location}` : ''}</Text></View><Text style={{ color: theme.text, fontWeight: '900', fontSize: 21 }}>{m.home_score}:{m.away_score}</Text></Pressable>)}</View> }
const s = StyleSheet.create({ fill: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, padding: 20 }, title: { fontSize: 24, fontWeight: '900', letterSpacing: -1 }, add: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, content: { padding: 20, gap: 22, paddingBottom: 32 }, stats: { flexDirection: 'row', borderRadius: 18, paddingVertical: 18 }, statValue: { color: '#fff', fontWeight: '900', fontSize: 23 }, statLabel: { color: 'rgba(255,255,255,.55)', fontSize: 11, marginTop: 3 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 15, padding: 15 }, bar: { width: 4, height: 35, borderRadius: 2 }, empty: { borderWidth: 1, borderRadius: 16, padding: 30, alignItems: 'center' } })
